config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'states#index'
  resources :info, only: [:index]
  resources :states, only: [:index, :show] do
    resources :breweries, only: [:index, :show, :redirect]
    resources :cities, only: [:show]
  end
  resources :search, only: [:index]
  resources :user_breweries, only: [:create]
  resources :users, only: [:index]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:search]
      @brewery_results = Brewery.search(params[:search]).order("created_at DESC")
    end
  end
end

app/views/search/index.html.erb
<div class = "row">
  <div class="large-12 columns">
    <form class= "small-12 large-6 columns search-form">
      <fieldset>
        <legend>Brewery Search</legend>
        <label>
          <%= form_tag(search_index_path, method: "get") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Enter brewery name here" %>
            <%= submit_tag "Search", name: nil, id: "search-form", style: 'background-color: #0F7D46' %>
          <% end %>
        </label>
      </fiedlset>
    </form>
  </div>
</div>

<div class ="row">
  <div class="large-12 columns">
    <% if @brewery_results %>
      <ul>
        <% @brewery_results.each do |result| %>
          <li>
            <%= link_to "#{result.name} - #{result.city.name}, #{result.state.name}", state_brewery_path(result.state_id, result.id) %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>