config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'states#index'
  resources :info, only: [:index]
  resources :states, only: [:index, :show] do
    resources :breweries, only: [:index, :show, :redirect]
    resources :cities, only: [:show]
  end
  resources :search, only: [:index]
  resources :user_breweries, only: [:create]
  resources :users, only: [:index]
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base

  def self.search(search)
    where("name ILIKE?", "%#{search}")
  end

  belongs_to :state
  belongs_to :city
end

app/controllers/breweries_controller.rb
require 'dotenv'
Dotenv.load

class BreweriesController < ApplicationController
  def index
    api_key = ENV['GOOGLE_MAP_API_TOKEN']
    @map_api_call = "https://maps.googleapis.com/maps/api/js?key=#{api_key}"
    @state = State.find(params[:state_id])
    @breweries = @state.breweries.sort_by &:name
    @cities = @state.cities.sort_by &:name
    location_builder = BuildLocationArray.new
    @brewery_location_array = location_builder.build_locations(
    @breweries
    ).to_json
  end

  def show
    @brewery = Brewery.find(params[:id])
    @user_brewery = UserBrewery.new
  end

  def redirect
    redirect_to state_brewery_path(params[:id])
  end
end

app/views/breweries/_single_brewery_map.html.erb
<div class= "hide-for-small large-5 columns" id="map-container">
  <div id="map-canvas"></div>
</div>

<script type="text/javascript" >
  var geocoder;
  var map;

  function initialize() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(<%= @brewery.latitude %>,<%= @brewery.longitude %> );

    var mapOptions = {
      zoom: 12,
      center: latlng
    }
    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

    var infowindow = new google.maps.InfoWindow();

    var marker = new google.maps.Marker({
     position: new google.maps.LatLng(<%= @brewery.latitude %>, <%= @brewery.longitude %>),
     map: map,
    });

  }


  function loadScript() {
   var script = document.createElement('script');
   script.type = 'text/javascript';
   script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp' +
       '&signed_in=true&callback=initialize';
   document.body.appendChild(script);
  }

  window.onload = loadScript;

</script>

app/views/breweries/_state_brewery_map.html.erb
<div class= "small-12-columns large-7 columns" id="map-container">
  <div id="map-canvas"></div>
</div>


<script type="text/javascript" >
  var geocoder;
  var map;

  function initialize() {
  geocoder = new google.maps.Geocoder();
  codeAddress();
  var latlng = new google.maps.LatLng(-34.397, 150.644);
  var mapOptions = {
    zoom: 6,
    center: latlng
  }
  map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

  var locations = <%= raw @brewery_location_array.as_json %>;
  var infowindow = new google.maps.InfoWindow();

   for (var i = 0; i < locations.length; i++) {
       var marker = new google.maps.Marker({
         position: new google.maps.LatLng(locations[i][1], locations[i][2]),
         map: map,
         url: locations[i][3]
       });

       google.maps.event.addListener(marker, 'mouseover', (function(marker, i) {
         return function() {
           infowindow.setContent(locations[i][0]);
           infowindow.open(map, marker);
         }
       })(marker, i));

      google.maps.event.addListener(marker, 'click', function() {
        window.location.href = this.url;
      });
    }
  }

  function codeAddress() {
    var state = " <%= @state.name %> ";
    geocoder.geocode( { 'address': state}, function(results, status) {

    var ne = results[0].geometry.viewport.getNorthEast();
    var sw = results[0].geometry.viewport.getSouthWest();

    var bounds = new google.maps.LatLngBounds(sw, ne);
    map.setCenter(bounds.getCenter());
  });
  }

  function loadScript() {
   var script = document.createElement('script');
   script.type = 'text/javascript';
   script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp' +
       '&signed_in=true&callback=initialize';
   document.body.appendChild(script);
  }

  window.onload = loadScript;

  // Listener on brewery dropdown. Links to brewery page on select

  $(function(){
    $('#brewery').bind('change', function () {
      var state = <%= @state.id %>;
       var url = "/states/" + state + "/breweries/" + $(this).val()
        if (url) {
            window.location.replace(url);
        }
        return false;
    });
  });

  // Listener on city dropdown. Links to city page on select

  $(function(){
    $('#cities').bind('change', function () {
      var state = <%= @state.id %>;
       var url = "/states/" + state + "/cities/" + $(this).val()
        if (url) {
            window.location.replace(url);
        }
        return false;
    });
  });

</script>

app/views/breweries/index.html.erb
<div class = "row">
  <div class="small-12 large-5 columns">
    <h1><%= @state.name %></h1>
    <h2>Search by brewery:</h2>
    <%= select_tag 'brewery', options_from_collection_for_select(@breweries, 'id', 'name'), include_blank: true %>
    <h2>Search by city:</h2>
    <%= select_tag 'cities', options_from_collection_for_select(@cities, 'id', 'name'), include_blank: true%>

  </div>

  <% if @brewery_location_array %>
    <%= render "state_brewery_map" %>
  <% end %>

</div>

app/views/breweries/show.html.erb
<div class = "row">
  <div class="small-12 large-7 columns" id="brew-info">
    <h1><%= @brewery.name %></h1>

    <ul class="fa-ul">
      <% if @brewery.city && @brewery.street_address %>
        <li>
          <%= fa_icon "location-arrow", text: "#{@brewery.street_address} #{@brewery.city.name}, #{@brewery.state.name}" %>
        </li>
      <% end %>

      <% if @brewery.website %>
        <li><%= fa_icon "external-link" %> <%= link_to "Website", (@brewery.website) %></li>
      <% end %>

      <% if @brewery.phone %>
        <li>
          <%= fa_icon "phone", text: @brewery.phone %>
        </li>
      <% end %>

      <% if @brewery.hours_of_operation %>
        <li><%= fa_icon "clock-o", text: @brewery.hours_of_operation %></li>
      <% end %>
    </ul>

    <%= link_to "#{@brewery.state.name} Page", state_breweries_path(@brewery.state), class: "button radius" %>

    <hr>

    <div id="reviews">
      <% if user_signed_in? %>
        <%= button_to "I visited this brewery", user_breweries_path(brewery_id: @brewery.id, method: :post) %>
      <% end %>

      <h5>Reviews coming soon!</h5>
    </div>
  </div>


  <div>
    <% if ( (@brewery.latitude != nil) && (@brewery.longitude != nil) ) %>
      <%= render "single_brewery_map" %>
    <% end %>
  </div>

</div>