config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'states#index'
  resources :info, only: [:index]
  resources :states, only: [:index, :show] do
    resources :breweries, only: [:index, :show, :redirect]
    resources :cities, only: [:show]
  end
  resources :search, only: [:index]
  resources :user_breweries, only: [:create]
  resources :users, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Beerica" %></title>
    <%= stylesheet_link_tag    "application", media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= favicon_link_tag 'beer.png' %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <nav class="top-bar hide-for-small" data-topbar role="navigation" data-options="sticky_on: large">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">BEERICA: Tracking the state of breweries by state</a></h1>
        </li>
      </ul>
    </nav>

    <nav class="top-bar small-12.columns hide-for-large hide-for-medium" data-topbar role="navigation" data-options="sticky_on: large">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">BEERICA</a></h1>
        </li>
      </ul>
    </nav>

    <div class="icon-bar four-up">
      <%= link_to root_path, {controller: "states", action: "index", id: "home"}, class: "item" do %>
        <%= image_tag "fi-home.svg" %>
        <label>Home</label>
      <% end %>

      <%= link_to info_index_path, {controller: "info", action: "index", id: "info"}, class: "item" do %>
        <%= image_tag "fi-magnifying-glass.svg" %>
        <label>Search</label>
      <% end %>

      <%= link_to info_index_path, {controller: "info", action: "index", id: "info"}, class: "item" do %>
        <%= image_tag "fi-info.svg" %>
        <label>About</label>
      <% end %>

      <% if user_signed_in? %>

        <%= link_to info_index_path, {controller: "info", action: "index", id: "info-2"}, class: "item" do %>
          <%= image_tag "fi-pencil.svg" %>
          <label>Log out</label>
        <% end %>

      <% else %>

        <%= link_to info_index_path, {controller: "info", action: "index", id: "info-2"}, class: "item" do %>
          <%= image_tag "fi-pencil.svg" %>
          <label>Log In</label>
        <% end %>

      <% end %>
    </div>

    <%= yield %>
    <%= stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>

  </body>
</html>